### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#102]
Currently when installing the latest version of WellcomeML v2020.7.0 the following error is thrown
```
ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.1 which is incompatible.
```

This does not cause an error in installation or usage as far as i have seen but it could create problems in packages that depend on WellcomeML. It would be ideal to pin all versions of our packages as a starting point but possibly also add a frozen requirements.txt into setup.py.

**Comment by aCampello** [comment]
I got something similar now:

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
```bash
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

botocore 1.17.31 requires docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.1 which is incompatible.
tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.5.2 which is incompatible.
```
