### ISSUE TITLE
Problems importing bert vectorizer on windows 

### ISSUE THREAD

**Issue by nonieA** [wellcometrust/WellcomeML#104]
When trying to import bert_vectorizer it shows the error 
`ImportError: cannot import name 'BertModel' from 'transformers' `
BertModel doesn't seem to exist in transformers. 

Looking at transformers.__init__.py it seems that BertModel is only imported if torch is available. 

Torch doesn't automatically install when installing wellcomeml in windows. I think this is because you have to pip install torch slightly differently in windows (`pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html`, from here - https://pytorch.org/). 

Even though I have installed torch separately transformers still wont import BertModel.

**Comment by aCampello** [comment]
Have you tried in stalling transformers *after* torch, i.e.:

```bash
pip install --no-cache-dir transformers==2.0.0
```
You might have to uninstall it and try it again.

**Comment by nonieA** [comment]
Thanks, this worked

**Comment by lizgzil** [comment]
is this something we should add in as logic to the Makefile so future Windows users don't have the same problem?

**Comment by aCampello** [comment]
I think it will be hard to add/test a make recipe to windows (if @nonieA wants to open a PR on that happy to do so), but as a minimum we could update the documentation to include this workaround.
