### ISSUE TITLE
Improve way to handle extras

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#125]
At the moment, the way to handle extras is to look whether we can import the functions, and if not, throw a warning.

That might hide other development errors that prevent from import the functions, which is not really related to extras

https://github.com/wellcometrust/WellcomeML/blob/2afcd74a8397b47c10ac1e227168c3ff7dd1f05d/wellcomeml/ml/__init__.py#L46-L47

Ideally we would like to show what is the error besides the warning.

**Comment by nsorros** [comment]
is this resolved by #262? @aCampello

**Comment by aCampello** [comment]
Partially. I think the idea was to have a better handling of extras in general, but that is addressed in other issues, so I think we can close this.
