### ISSUE TITLE
CNN and BiLSTM should be able to accept X and Y as lists

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#131]
Currently the models require passing a numpy array but they should work with python lists as well.

One easy fix is to convert at the start.

Currently the functions that require update are:

- [ ] CNN fit: https://github.com/wellcometrust/WellcomeML/blob/84ea8b9365ec5f3506b1fee598f7fdb3caf933cd/wellcomeml/ml/cnn.py#L170 (which also requires fix to _yield_data)
- [ ] CNN predict:
https://github.com/wellcometrust/WellcomeML/blob/84ea8b9365ec5f3506b1fee598f7fdb3caf933cd/wellcomeml/ml/cnn.py#L212
- [ ] CNN score:
https://github.com/wellcometrust/WellcomeML/blob/84ea8b9365ec5f3506b1fee598f7fdb3caf933cd/wellcomeml/ml/cnn.py#L224

- [ ] BiLSTM fit:
https://github.com/wellcometrust/WellcomeML/blob/84ea8b9365ec5f3506b1fee598f7fdb3caf933cd/wellcomeml/ml/bilstm.py#L141
- [ ] BiLSTM predict:
https://github.com/wellcometrust/WellcomeML/blob/84ea8b9365ec5f3506b1fee598f7fdb3caf933cd/wellcomeml/ml/bilstm.py#L185
- [ ] BiLSTM score:
https://github.com/wellcometrust/WellcomeML/blob/84ea8b9365ec5f3506b1fee598f7fdb3caf933cd/wellcomeml/ml/bilstm.py#L197

**Comment by Xx-Ashutosh-xX** [comment]
@nsorros we can just convert the list to a NumPy array and it will work. I haven't looked at what are the features of the input But, I would be able to do this.

**Comment by Xx-Ashutosh-xX** [comment]
I am not that versed with open source but am quite knowledgeable in the field of deep learning, So I might require some help.

**Comment by aCampello** [comment]
Hi @Xx-Ashutosh-xX , I updated the description to point at the exact classes that need updating. @nsorros  can you double check?

**Comment by aCampello** [comment]
Happy to help you - if you open a PR with one of the updates above, we can comment on your code and give tips.

**Comment by Xx-Ashutosh-xX** [comment]
sure, will do

**Comment by nsorros** [comment]
@Xx-Ashutosh-xX Yep, this should be the easiest fix. It would be great to have some additional tests for this addition but other than that, I think it is straightforward.

@aCampello thanks for adding the specific places, they look good.
