### ISSUE TITLE
Write better description for hacktoberfest issues

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#145]
- [x] #131 
- [x] #125 
- [x] #122 
- [x] #103 
- [x] #80 
- [x] #79 
- [x] #74 
- [x] #60 
- [x] #45 
- [x] #35

**Comment by aCampello** [comment]
I'm on 125, 122, 80 at the moment

**Comment by lizgzil** [comment]
@nsorros and @aCampello I've edited 103, 60, 45, 32 , but since they weren't my issues you might want to double check I've interpreted them correctly.

**Comment by nsorros** [comment]
> @nsorros and @aCampello I've edited 103, 60, 45, 32 , but since they weren't my issues you might want to double check I've interpreted them correctly.

done

**Comment by nsorros** [comment]
i remove #61 as it is more complicated that initially thought. i did add more details though.

**Comment by nsorros** [comment]
removed #77 as problems seems to have dissapeared as @lizgzil found out
