### ISSUE TITLE
Upgrade to spacy nightly?

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#167]
Spacy 3.0 has native support to transformers 3.0.0. There seems that there are a couple of issues related do spacy not talking 
to the correct versions to transformers.

Should we update everything to 3.0.0?

**Comment by aCampello** [comment]
@nsorros @lizgzil

**Comment by nsorros** [comment]
Is it native support or through spacy-transformers? I think the latter

**Comment by aCampello** [comment]
Right, the latter, but you don't need to add/pin space-transformers as a dependency anymore.

**Comment by nsorros** [comment]
> Right, the latter, but you don't need to add/pin spacy-transformers as a dependency anymore.

true

**Comment by nsorros** [comment]
Steps

- [ ] Upgrade to spacy v2.3 and transformers < 2.9 which are both supported by spacy-transformers 0.6
- [ ] Ugrade to spacy v3 and transformers v3.0 and spacy-transformers v1.0

**Comment by aCampello** [comment]
Here is a list of tests that fail for now:

Let's fix one by one:

- [ ] tests/test_bert_classifier.py::test_multilabel SKIPPED
- [ ] tests/test_bert_classifier.py::test_partial_fit SKIPPED
- [ ] tests/test_bert_classifier.py::test_scibert SKIPPED
- [ ] tests/test_clustering.py::test_full_pipeline[tsne-True] FAILED
- [ ] tests/test_clustering.py::test_full_pipeline[umap-True] FAILED
- [ ] tests/test_clustering.py::test_full_pipeline[umap-False] FAILED
- [ ] tests/test_clustering.py::test_parameter_search[tsne] FAILED
- [ ] tests/test_clustering.py::test_parameter_search[umap] FAILED
- [ ] tests/test_ner_spacy.py::test_fit FAILED
- [ ] tests/test_ner_spacy.py::test_predict FAILED
- [ ] tests/test_ner_spacy.py::test_score FAILED
- [ ] tests/test_ner_spacy.py::test_ner_classification_report FAILED
- [ ] tests/test_spacy_classifier.py::test_multilabel FAILED
- [ ] tests/test_spacy_classifier.py::test_multilabel_Y_list FAILED
- [ ] tests/test_spacy_classifier.py::test_partial_fit FAILED
- [ ] tests/test_vectorizer.py::test_tf_idf_dispatch FAILED
- [ ] tests/test_vectorizer.py::test_vectorizer_that_does_not_have_save FAILED
