### ISSUE TITLE
Bert vectorizer count of max tokens is wrong

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#173]
https://github.com/wellcometrust/WellcomeML/blob/16754b0a9806b29b942a4ac67ba9b67253ce97fc/wellcomeml/ml/bert_vectorizer.py#L43

This lines tries to ensure that a max of 512 tokens are passed to BERT but tokens are not number of characters but number of words or subwords to be exact. The most accurate way to count them would be to tokenize using the bert tokenizer but we could also approximate by `x.split()`

**Comment by aCampello** [comment]
I am not sure if that line is even needed. You can set `max_position_embeddings` on `self.model` if you want to embed a text with more than 512 words, otherwise, I think we should just cut the tokenised text. i.e., after
```
tokenized_x = self.tokenizer.tokenize("[CLS] " + x + " [SEP]")
```

do something like

```
if len(tokenized_x) > 512:
tokenized_x = tokenized_x[0] + tokenized_x[1:510] + tokenized_x[-1] # Note that we need this to preserve the token for [SEP]
```

I am sure there must be more elegant ways, but the idea of just cutting the text is what I'd go for.

**Comment by nsorros** [comment]
> I am not sure if that line is even needed. You can set `max_position_embeddings` on `self.model` ~if you want to embed a text with more than 512 words~ (this only works if you are re-training from scratch). I think we should just cut the tokenised text. i.e., after
> 
> ```
> tokenized_x = self.tokenizer.tokenize("[CLS] " + x + " [SEP]")
> ```
> 
> do something like
> 
> ```
> if len(tokenized_x) > 512:
>     tokenized_x = tokenized_x[0] + tokenized_x[1:510] + tokenized_x[-1] 
> # Note that we need this to preserve the token for [SEP]
> ```
> 
> I am sure there must be more elegant ways, but the idea of just cutting the text is what I'd go for.

i agree with your solution, i will open a PR to address this

**Comment by nsorros** [comment]
For some reason the BertClassifier does not suffer from that problem
