### ISSUE TITLE
HDBScan numpy C header error

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#197]
Reproducing the error.
```
pip install numpy==1.19.2 hdbscan
python -c "import hdbscan"
```
throws
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nicksorros/code/test/pip_problem/venv/lib/python3.7/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/Users/nicksorros/code/test/pip_problem/venv/lib/python3.7/site-packages/hdbscan/hdbscan_.py", line 21, in <module>
    from ._hdbscan_linkage import (single_linkage,
  File "hdbscan/_hdbscan_linkage.pyx", line 1, in init hdbscan._hdbscan_linkage
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

This is issue is mentioned in hdbscan issue tracker https://github.com/scikit-learn-contrib/hdbscan/issues/457

**Comment by nsorros** [comment]
Our current workaround is to disable hdbscan from the clustering module.

**Comment by nsorros** [comment]
There is a potential solution in the issue which is installing hdbscan separately through `pip install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation`

**Comment by lizgzil** [comment]
@nsorros do you mean similar to this bit https://github.com/wellcometrust/WellcomeML/blob/493e977e360f91d004acaf7cd7fd88bcb0171801/wellcomeml/ml/sent2vec_vectorizer.py#L16

```
        try:
            import sent2vec
        except ImportError:
            from wellcomeml.__main__ import download

            download("non_pypi_packages")
            import sent2vec
```
?
I like that way. If they havent built build/virtualenv then I don't think this won't work anyway. So not sure if it will mess up another venv they might be using?

**Comment by nsorros** [comment]
> @nsorros do you mean similar to this bit
> 
> https://github.com/wellcometrust/WellcomeML/blob/493e977e360f91d004acaf7cd7fd88bcb0171801/wellcomeml/ml/sent2vec_vectorizer.py#L16
> 
> ```
>         try:
>             import sent2vec
>         except ImportError:
>             from wellcomeml.__main__ import download
> 
>             download("non_pypi_packages")
>             import sent2vec
> ```
> 
> ?
> I like that way. If they havent built build/virtualenv then I don't think this won't work anyway. So not sure if it will mess up another venv they might be using?

I am mainly thinking that some of the dependencies of hdbscan might interfere with other dependencies in the project
