### ISSUE TITLE
Pip new dependency resolver takes hours

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#198]
Reproducing the error. Python 3.7.9. Pip 20.3.3
```
pip install spacy-transformers==0.6.1 tokenizers==0.10.0
```

To be fair spacy-transformers depends on a version transformers (<=2.9) that depends on a version of tokenizers (<=0.5.2) which is incompatible. But this should just trigger an incompatibility error in due time. Instead pip goes on a cycle of trying an extensive range of dependencies which takes hours.

Running `pip install spacy-transformers==0.6.1 tokenizers` does not trigger that behaviour 

Running `pip install -r requirements.txt` with the following requirements file
```
# requirements.txt
spacy-transformers==0.6.1
transformers<=2.9
tokenizers==0.10.0
```
throws this ERROR quickly
```
ERROR: Cannot install -r requirements.txt (line 4) and tokenizers==0.10.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tokenizers==0.10.0
    transformers 2.8.0 depends on tokenizers==0.5.2
    The user requested tokenizers==0.10.0
    transformers 2.7.0 depends on tokenizers==0.5.2
    The user requested tokenizers==0.10.0
    transformers 2.6.0 depends on tokenizers==0.5.2
    The user requested tokenizers==0.10.0
    transformers 2.5.1 depends on tokenizers==0.5.2
    The user requested tokenizers==0.10.0
    transformers 2.5.0 depends on tokenizers==0.5.0
    The user requested tokenizers==0.10.0
    transformers 2.4.1 depends on tokenizers==0.0.11
    The user requested tokenizers==0.10.0
    transformers 2.4.0 depends on tokenizers==0.0.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by nsorros** [comment]
Good news is that the latest spacy-transformers and almost lately tokenizers work well together from the eyes of the pip dependency resolver at least

`pip install spacy-transformers==1.0.0 tokenizers==0.9.4` works fine

**Comment by jdu** [comment]
Yeah, this looks like the specific version of tokenizer in requriements.txt has a conflicting dependency then. So maybe transformers has a strict dependency requirement on an older version of tokenizers then?

**Comment by nsorros** [comment]
We have resolved this by pinning the correct dependencies, will reopen if we experience that problem again
