### ISSUE TITLE
Use semantic versioning instead of CalVer

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#202]
CalVer has the advantage that we easily get to know when the version was published. However, it hides whether the release only contains minor changes or big changes, esp. when a big feature is merged (e.g. the latest merge to SpaCy v3).

We can keep both of the worlds by using Semantic and forcing the CHANGELOG.md to contain the dates of the release.

**Comment by aCampello** [comment]
@nsorros @lizgzil

**Comment by nsorros** [comment]
I think this is a sensible change. Additionally i find it easier to remember which versions introduced which features when versions follow more standard versioning, thinking of spacy v2.3 or tensorflow 2.4 etc

**Comment by lizgzil** [comment]
yep makes sense to me. What number should we start with though? 1.0 seems weird because it's not brand new, but I suppose it would also be weird to do 2.0 without a 1.0!

**Comment by nsorros** [comment]
I am afraid that switching to standard versioning will mesh up what happens when someone pip installs without a version i.e. the sorting of the latest packages will be wrong.

**Comment by lizgzil** [comment]
'mesh up' - you've been working on your tags for too long 😆 
oh dear, good point. well do we need the 'v'? e.g. does '1.1' come before 'v2012' in sort order?

**Comment by nsorros** [comment]
> 'mesh up' - you've been working on your tags for too long 😆
> oh dear, good point. well do we need the 'v'? e.g. does '1.1' come before 'v2012' in sort order?

we need to check

**Comment by aCampello** [comment]
I think pip will be ok - I'd guess they order by release date rather than number version, but yes would be good to double check.

I vote to start at 1.0.0 and treat everything before it as "pre-releases".

**Comment by nsorros** [comment]
> I think pip will be ok - I'd guess they order by release date rather than number version, but yes would be good to double check.
> 
> I vote to start at 1.0.0 and treat everything before it as "pre-releases".

If there is not problem with sorting then sounds good to me

**Comment by aCampello** [comment]
Ok, we might have a problem with this. It seems that pypi puts it below all of them.
<img width="876" alt="Screenshot 2021-02-23 at 16 59 31" src="https://user-images.githubusercontent.com/27929341/108878871-95c53280-75f8-11eb-9f6f-6f4b4c4cf95f.png">

**Comment by aCampello** [comment]
Ok. I have a solution for this. We can "yank" a version, which means it won't be able to appear in the public pypi list, however it will still be available using `wellcomeml=2020.5.0` for example. What do you think? 
<img width="819" alt="Screenshot 2021-02-23 at 17 05 20" src="https://user-images.githubusercontent.com/27929341/108879627-59de9d00-75f9-11eb-9e95-1b19e9b549a8.png">

**Comment by lizgzil** [comment]
ok, so basically it won't break anyones code if they specified an old version, but if they browse pypi they won't see the old versions?

seems fine to me to do this, will definitely be nice to use semantic versioning and have it at the top of the list.

**Comment by aCampello** [comment]
Yes, that's right. And we can switch to GitHub releases too (as opposed to pre-releases), so I think the story will actually be ok:

- We were using CalVER when we had pre-releases
- Now we have releases, we are using Semantic Versioning.

**Comment by ivyleavedtoadflax** [comment]
Yesssssssss :clap: :clap:

**Comment by nsorros** [comment]
> Ok. I have a solution for this. We can "yank" a version, which means it won't be able to appear in the public pypi list, however it will still be available using `wellcomeml=2020.5.0` for example. What do you think?
> <img alt="Screenshot 2021-02-23 at 17 05 20" width="819" src="https://user-images.githubusercontent.com/27929341/108879627-59de9d00-75f9-11eb-9e95-1b19e9b549a8.png">

what happens if someone runs `pip install wellcomeml`?

**Comment by aCampello** [comment]
It will install the latest `non-yanked` solution.  (in this case 1.0).

**Comment by nsorros** [comment]
> It will install the latest `non-yanked` solution. (in this case 1.0 if we do it to all of the CalVer ones).

In this case, yanking might be the only way, nice find @aCampello

**Comment by nsorros** [comment]
Let's go for it

**Comment by aCampello** [comment]
Fixed in https://github.com/wellcometrust/WellcomeML/pull/231
