### ISSUE TITLE
Explicit python version in Makefile

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#224]
At the moment we use `python3` as our python version in Makefile
https://github.com/wellcometrust/WellcomeML/blob/9acf7cea9641000980e5bb4bfe80daebc5c5e5c9/Makefile#L4

This is not reproducible as each of us including travis might be running on a different python. We force travis to try python 3.7 and 3.8 which is a good thing but we should also ensure our env is created with one version.

An added benefit of this is that brew cannot mess up your python as python3.8 should link to one version compared to python3 that might be updated to point to the latest.

**Comment by aCampello** [comment]
agree, but what should be the default? 3.8? 

Note that this is only for dev purposes.

**Comment by nsorros** [comment]
> agree, but what should be the default? 3.8?
> 
> Note that this is only for dev purposes.

Agree on it being only for dev purposes.

I am happy with either 3.8 or 3.7, I have both versions intalled. @lizgzil?

**Comment by lizgzil** [comment]
I use 3.7. I have bad feelings about 3.8 after that horrible bug I had last year - but that was to do with a stray init file in the end (I seem to remember) so either are actually fine!

**Comment by aCampello** [comment]
If everyone is fine with both, let's use 3.8. We currently added support to 3.8, so probably better to keep up-to-date (as 3.9 is under development, and it would be easier to make the gap).
