### ISSUE TITLE
Spacy complains about W108 in travis logs

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#230]
After merging #229, I noticed that now logs contain a lot of complains from Spacy. Is this something we want to silence or resolve? Assigning to @aCampello as it appears on test_clustering but applicable to all @lizgzil 

![Screenshot 2021-02-24 at 11 31 12 AM](https://user-images.githubusercontent.com/4975761/108980022-eb025200-7693-11eb-9e80-32c135f5f608.png)

**Comment by aCampello** [comment]
This has been addressed by the use of the new lemmatised in space #272  is no longer the case.
