### ISSUE TITLE
Is Deep Learning really an extra?

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#234]
I think in the beginning we were thinking of using wellcomeml for IO operations as well, however I myself never `pip install wellcomeml` without extras. I wonder if it is time to promote deep learning as the core library, and leave the extras for any real extras we might want to add.

**Comment by aCampello** [comment]
@nsorros @lizgzil

**Comment by nsorros** [comment]
It is a fair point. There is another reason for the deep learning extra though, this is that the deep learning libraries are quite heavy in terms of size so if we believe that there is value to wellcomeml without the deep learning extra then there is an argument towards keeping it.

Actually personally, I want to move towards the direction of adding more extras that allow more control to the user about what libraries are needed, for example tensorflow, torch, spacy, transformers. These are all heavy libraries that do not all need to be installed to use one class from the library.

**Comment by aCampello** [comment]
I agree with breaking down into different functionalities, although I have the feeling that we are going to need a good handler in `__ini__.py`, or a re-factor of the folders, to make this happen.

But the way it stands now (deep-learning vs non-deep-learning), I suppose `deep-learning` would be the "default"

**Comment by nsorros** [comment]
So the non deep-learning libraries now are
```
from .frequency_vectorizer import WellcomeTfidf
from .doc2vec_vectorizer import Doc2VecVectorizer
from .sent2vec_vectorizer import Sent2VecVectorizer
from .voting_classifier import WellcomeVotingClassifier
```
and to be fair doc2vec and sent2vec are deep learning related even though they do not require the heavy deep learning libraries so agree that it seems to be the default.

I am happy with the proposed change, you have the green light from me ✅
