### ISSUE TITLE
Introduce additional extras to provide better control of which libraries are installed

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#285]
This is related to #234 and to a certain extent assumes that `deep-learning` will be deprecated in favour of more refined extras.

We need to discuss our motivation for doing so to frame the discussion. A lot of libraries provide a level of control about which libraries are installed with extras for example spacy (spacy[lookups, cuda,...]), dvc (dvc[s3]). I think the rationale in most cases is that there is a core functionality that most users need and some additional functionality that is left as extra to reduce the size of the library and possibly import time as this is not always needed.

I think in our case our main concern has always been the size of WellcomeML due to the heavy deep learning libraries such as tensorflow and torch. As such possibly the size of the libraries and where and how they are used is a good farming of the conversation. For example if we are to remove tensorflow, what functionality is left and to which extent it is a core library we depend on. 

We can inspect the size of the library (WellcomeML) and individual dependencies through the virtualenv that it creates, even though few of those dependencies are not always installed like the test dependencies. The size of the virtualenv is ~2GB which makes WellcomeML quite heavy. The biggest libraries we depend on are
* tensorflow 760MB (with some additional that take more space e.g. tensorboard 30M)
* torch 388MB
* spacy 75MB
* pandas 51MB
* sklearn 31MB
* transformers  15MB
* scipy 126MB
This is not a completely accurate image as each of these libraries have further dependencies but it gives us an estimate.

Unsurprisingly the biggest problem is caused by tensorflow and torch followed by spacy and in particular tensorflow. Unfortunately tensorflow is being used far more than torch. Personally I think libraries below 100MB are not a problem at this point including scipy.

**tensorflow**
```
wellcomeml/ml/attention.py:import tensorflow as tf
wellcomeml/ml/bert_classifier.py:import tensorflow as tf
wellcomeml/ml/bert_semantic_equivalence.py:import tensorflow as tf
wellcomeml/ml/bilstm.py:import tensorflow as tf
wellcomeml/ml/cnn.py:import tensorflow_addons as tfa
wellcomeml/ml/cnn.py:import tensorflow as tf
wellcomeml/ml/keras_utils.py:import tensorflow as tf
```

**torch**
```
wellcomeml/ml/bert_vectorizer.py:import torch
wellcomeml/ml/spacy_classifier.py:import torch
```

**spacy**
```
wellcomeml/ml/frequency_vectorizer.py:#import spacy
wellcomeml/ml/spacy_classifier.py:import spacy
wellcomeml/ml/spacy_entity_linking.py:import spacy
wellcomeml/ml/spacy_knowledge_base.py:import spacy
wellcomeml/ml/spacy_ner.py:import spacy
```

## Suggestions
Most of our code at the moment depends on tensorflow so I am not sure we can eliminate that, we can definitely make it an explicit extra though and throw an error if the user tries to import a library that needs it. But is it an extra?

We can do the same for spacy. Spacy I think is definitely an extra library for WellcomeML (personal opinion @lizgzil may feel different). In any case if we make tensorflow an extra, I do not see why we should not make spacy also.

Lastly torch is only used in two places and I feel like it can be eliminated. Bert vectorizer can switch to using tensorflow or at least import torch only if needed (maybe scibert is only torch). Then spacy classifier uses torch for GPU only so again we can import if needed or investigate using tensorflow if possible.

Note that transformers does not install tensorflow or torch even though it needs one of them to run. So a completely different avenue is to leave that to the user and just throw a warning that a library is needed. Not sure if this is the right direction.

**Comment by nsorros** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add extras to WellcomeML to make installation more light and allow user to determine what they need](https://trello.com/c/mARL7xw7/1237-add-extras-to-wellcomeml-to-make-installation-more-light-and-allow-user-to-determine-what-they-need)

**Comment by aCampello** [comment]
I'm happy for users using tensorflow to pay the price of importing it, the same with spacy, etc, but not vice-versa. For example, users of WellcomeVotingClassifier have to pay the price of importing both, which in my local machine is around 10 seconds, besides a big virtualenv. I agree with `tensorflow, torch` and `spacy` being extras, and everything else being part of "core", since they are smaller.

For this to be effective, I think we need to somehow disable `__init__.py` as well #284. If we don't want to go to the avenue of being backwards incompatible, we can achieve this by accepting a `env` variable that will switch __init__ off, then throw a future warning.

**Comment by aCampello** [comment]
For a full picture, stripping all tensorflow and spacy dependencies give:

```
2.1G	Full venv
1.3G	.[tensorflow]
761M	.[spacy]
549M	Vanilla
```

I think that's a substantial reduction in size.

**Comment by nsorros** [comment]
> For a full picture, stripping all tensorflow and spacy dependencies give:
> 
> ```
> 2.1G	Full venv
> 1.3G	.[tensorflow]
> 761M	.[spacy]
> 549M	Vanilla
> ```
> 
> I think that's a substantial reduction in size, especially for spacy users, but even for tensorflow users (almost 1G reduction).

Suggestion makes sense. Let's do it. Let's be backwards incompatible.
