### ISSUE TITLE
Add WellcomeML to pypi

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#29]
As described above

**Comment by aCampello** [comment]
I investigated this a little bit, and it seems that PyPi does not allow for explicit dependency references such as: 

```
'en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz#egg=en_core_web_sm'
```

We would perhaps have to develop a CLI (similarly to spacy's download) and remove that from the reference.

**Comment by aCampello** [comment]
@nsorros do we still need that spacy transformers for:

```bash
'spacy-transformers @ https://github.com/nsorros/spacy-transformers/tarball/master#egg=spacy-transformers'
```

Or have they fixed the issue?

**Comment by nsorros** [comment]
> @nsorros do we still need that spacy transformers fork:
> 
> ```shell
> 'spacy-transformers @ https://github.com/nsorros/spacy-transformers/tarball/master#egg=spacy-transformers'
> ```
> 
> Or have they fixed the issue?

Need to check. Will get back on that.

**Comment by aCampello** [comment]
We are now on pypi http://pypi.org/project/wellcomeml/ 🎉
