### ISSUE TITLE
Add native HuggingFace Scibert support

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#33]
In light of https://github.com/allenai/scibert/commit/7598219a8d80b9c2fe1323a141e4a9e40ec044cb, and the closed issue https://github.com/allenai/scibert/issues/71, we don't need cache for Scibert anymore.

It could still be useful to have the "download_and_cache" function if we need another model, but for the time being we can turn it off for Scibert.

**Comment by nsorros** [comment]
I think this is slightly more complicated as we do not use hugging face directly but spacy transformers. We should of course move towards hugging face slowly as this will give us more control but for the time being I am not sure if we can leverage the integration. Need to investigate.

**Comment by aCampello** [comment]
I think some parts of the code, including the `BertVectorizer` and the `SemanticSimilarityClassifier` can already use the native hugging face. The only blocker is space transformers. In their next release, they are likely to support new versions of transformers (https://github.com/explosion/spacy-transformers/blob/bf729718502053ac9bd8770fc67aaeb549593510/requirements.txt#L2), so after that we can probably try to tackle this issue again.

**Comment by aCampello** [comment]
I am hoping this will be doable with the new spacy-transformers.
