### ISSUE TITLE
Add parameters for word embeddings to KerasVectorizer

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#35]
#### Description

When `build_embedding_matrix(embeddings_path)` is called - if embeddings_path is not found then download the word embedding given in parameter `word_vectors`. Default is `word_vectors=glove`.

#### Files

https://github.com/wellcometrust/WellcomeML/blob/127c6110732f993f41bfa1123ca594ee0027170e/wellcomeml/ml/keras_vectorizer.py#L24

#### Tasks

- [ ] Add `word_vectors` parameter to `build_embedding_matrix`
- [ ] Add test to https://github.com/wellcometrust/WellcomeML/blob/master/tests/test_keras_vectorizer.py to deal with case where the file isn't found in `build_embedding_matrix`

#### Original issue

Add parameter `word_vectors=glove` that downloads vectors if not available and creates embedding matrix

**Comment by aCampello** [comment]
When we do this, can we add some tests to KerasVectorizer? I think it's one with very small coverage.

**Comment by nsorros** [comment]
👍

**Comment by lizgzil** [comment]
@nsorros I've kept your original issue wording at the bottom of the description - please can you check whether my interpretation is correct

**Comment by nsorros** [comment]
> @nsorros I've kept your original issue wording at the bottom of the description - please can you check whether my interpretation is correct

perfect

**Comment by nsorros** [comment]
@lizgzil i think this is resolved
