### ISSUE TITLE
io function write_jsonl not working as expected 

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/WellcomeML#58]
I just did 
```
from wellcomeml.io import write_jsonl
entities = {'123': [[10, 0, 3, 4], [1, 4, 7, 2]], '345': [[20, 1, 3, 4], [44, 4, 7, 2]]}
write_jsonl(entities, output_file)
```
but `output_file` saved was:
```
[[10, 0, 3, 4], [1, 4, 7, 2]]
[[20, 1, 3, 4], [44, 4, 7, 2]]
```
i.e. keys weren't included. I assume this isn't the expected behaviour as often the keys are still needed?

**Comment by ivyleavedtoadflax** [comment]
From memory, the input should be a list of `dict`s rather than a dict

**Comment by lizgzil** [comment]
@ivyleavedtoadflax ah ha! ok well I will keep this open as a reminder to edit the function description.

**Comment by ivyleavedtoadflax** [comment]
Good idea 👍. I think also technically the output that your got is a valid JSON, just an array of arrays.
