### ISSUE TITLE
SciBertClassifier does not work with spacy-transformers 0.5.2

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#68]
One easy to reproduce this is by adding a parameter `pretrained="scibert"` to the test for bert_classifier. This throws `ValueError: Unsupported transformers config name: 'models/scibert_scivo...`

One way of resolving this for now is to pin the version to 0.5.1.

**Comment by aCampello** [comment]
This is a nightmare.

**Comment by nsorros** [comment]
I think this is resolved by #190
