### ISSUE TITLE
last_cls option breaks in BertVectorizer

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/WellcomeML#7]
I got an error using the 'last_cls' option when running the BertVectorizer in my entity linking project.
The error was:
```
   return embedded_a + embedded_b
ValueError: operands could not be broadcast together with shapes (88320,) (38400,)
```
The other options work fine. I can investigate more, just wanted to record it down for now.

**Comment by aCampello** [comment]
Ok, I understand the problem here. When using `last_cls` the tensor returned depends on the number of tokens (at the moment `number_of_tokens x dimension (768)`. I am not really sure what was the original intention here, but the result should be pooled/maxed over the tensor token dimension
