### ISSUE TITLE
BertVectorizer save and load

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#77]
#### Description

Atm when pickling a pipeline that contains the BertVectorizer this warning is being thrown
```
FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
  warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
```

It would be nice to expose a way to save and load BertVectorizer so that we can save the components independently when this warning materialises

#### Files

https://github.com/wellcometrust/WellcomeML/blob/6378d116f36ad7230cbc987ebede3d1aa28892ba/wellcomeml/ml/bert_vectorizer.py#L15

**Comment by lizgzil** [comment]
@nsorros I just did 
```
import pickle

from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

from wellcomeml.ml import BertVectorizer

X = [
    "Elizabeth is the queen of England",
    "Felipe is the king of Spain",
    "I like to travel",
]
y = [1, 1, 0]

pipeline = Pipeline([("bert", BertVectorizer()), ("svm", SVC(kernel="linear"))])
pipeline.fit(X, y)

with open('pipelinebert.pkl', 'wb') as output:
    pickle.dump(pipeline, output)
```
and didn't get that warning. Is this not what you meant in the issue?

**Comment by nsorros** [comment]
> import pickle
> 
> from sklearn.pipeline import Pipeline
> from sklearn.svm import SVC
> 
> from wellcomeml.ml import BertVectorizer
> 
> X = [
>     "Elizabeth is the queen of England",
>     "Felipe is the king of Spain",
>     "I like to travel",
> ]
> y = [1, 1, 0]
> 
> pipeline = Pipeline([("bert", BertVectorizer()), ("svm", SVC(kernel="linear"))])
> pipeline.fit(X, y)
> 
> with open('pipelinebert.pkl', 'wb') as output:
>     pickle.dump(pipeline, output)

That is what I meant yes. I tried your code and there was not issue even though torch version was 1.6 so closing.
