### ISSUE TITLE
Fix docstrings

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#80]
If you try to re-generate the docs by using the process in `README.md` (i.e. by running `make virtualenv` and then `make update-docs`), you get some warnings due to weird indentation of docstrings.

The objective of the issue is to fix some of them (all the ones related to docstrings). In particular:

- [ ] `/Users/campea/WellcomeML/wellcomeml/datasets/winer.py:docstring of wellcomeml.datasets.winer.create_train_test:11: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/datasets/winer.py:docstring of wellcomeml.datasets.winer.create_train_test:12: WARNING: Block quote ends without a blank line; unexpected unindent.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/io/s3_policy_data.py:docstring of wellcomeml.io.s3_policy_data.PolicyDocumentsDownloader:3: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/io/s3_policy_data.py:docstring of wellcomeml.io.s3_policy_data.PolicyDocumentsDownloader.download:3: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/io/s3_policy_data.py:docstring of wellcomeml.io.s3_policy_data.PolicyDocumentsDownloader.get_hashes:3: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/io/s3_policy_data.py:docstring of wellcomeml.io.s3_policy_data.PolicyDocumentsDownloader.get_hashes:4: WARNING: Block quote ends without a blank line; unexpected unindent.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/cnn.py:docstring of wellcomeml.ml.cnn:5: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/cnn.py:docstring of wellcomeml.ml.cnn:6: WARNING: Block quote ends without a blank line; unexpected unindent.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/cnn.py:docstring of wellcomeml.ml.cnn:8: WARNING: Definition list ends without a blank line; unexpected unindent.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/cnn.py:docstring of wellcomeml.ml.cnn:10: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/keras_utils.py:docstring of wellcomeml.ml.keras_utils.CategoricalMetrics.update_state:5: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/keras_utils.py:docstring of wellcomeml.ml.keras_utils.CategoricalMetrics.update_state:10: WARNING: Enumerated list ends without a blank line; unexpected unindent.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/spacy_entity_linking.py:docstring of wellcomeml.ml.spacy_entity_linking.SpacyEntityLinker.predict:3: WARNING: Unexpected indentation.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/spacy_entity_linking.py:docstring of wellcomeml.ml.spacy_entity_linking.SpacyEntityLinker.predict:6: WARNING: Block quote ends without a blank line; unexpected unindent.`
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/spacy_knowledge_base.py:docstring of wellcomeml.ml.spacy_knowledge_base.SpacyKnowledgeBase.train:3: WARNING: Unexpected indentation.
- [ ] `/Users/campea/WellcomeML/wellcomeml/ml/spacy_knowledge_base.py:docstring of wellcomeml.ml.spacy_knowledge_base.SpacyKnowledgeBase.train:7: WARNING: Definition list ends without a blank line; unexpected unindent.`
```

**Comment by Ahmeed2m** [comment]
I can work on this one for Hacktoberfest.
If you can assign it to me, please do. Also let me know which branch is the target branch for the PR and if you have any contribution rules you apply.

**Comment by Ahmeed2m** [comment]
Was this solved? I don't see any flake8 warnings as of now

**Comment by aCampello** [comment]
I @Ahmeed2m, thanks for your interest! I am writing better descriptions for the issues and will let you know. As far as I know this hasn't been solved yet.

**Comment by aCampello** [comment]
I checked again. This happens when trying to generate the docs with `make update-docs`. I can assign it to you if you are still up for it. 

Then just submit a PR and we'll review it.

**Comment by Xx-Ashutosh-xX** [comment]
Was this solved?

**Comment by aCampello** [comment]
Yes, it will be completed by #153
