### ISSUE TITLE
Upgrade to latest transformers and spacy-transformers

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#82]
Currently both libraries are pinned to a lower version to ensure our code works as it was developed with these versions in mind and both libraries introduce significant changes in each version. When updating the functionality of the classes needs to be checked and if there is a problem that is not catched by tests, a test should be added

Updating might resolve #33 and is related to #76 and #75

**Comment by aCampello** [comment]
Seems that `spacy-nightly` uses transformers 3.0.0.

**Comment by nsorros** [comment]
I aim to address this, this month

**Comment by nsorros** [comment]
This has been addressed after upgrading to spacy v3
