### ISSUE TITLE
Create release 2020.07.0

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#99]
Models
---
* Adds Doc2VecVectorizer
* Adds WellcomeVotingClassifier
* Adds Sent2VecVectorizer
* Adds SemanticEquivalenceMetaClassifier
* Adds CategoricalMetrics and MetricMiniBatchHistory

Datasets
---
* Adds CONLL dataset
* Adds Winer dataset

Features
---
* Automatically load models like en_core_web_sm and en_trf_bertbaseuncased_lg but also download packages like sent2vec, only when needed
* Adds docs based on sphinx and read the docs

Repo
---
* Adds pep8 / flake8 checks and address violations
* Adds badges for build, codecov and license
* Adds pull request template that forces link to issue or trello

Bugs
---
* Fix dependency on non pypi packages for tests
* Pin spacy transformers to 0.5.1 
* Fix codecov running in separate travis venv

**Comment by nsorros** [comment]
@aCampello @lizgzil let me know if I am forgetting anything

**Comment by lizgzil** [comment]
The `Automatically load models like en_core_web_sm and en_trf_bertbaseuncased_lg but also download packages like sent2vec` comment could do with a 'when needed' addition at the end? Otherwise people might be worried they are about to load some massive models if they install wellcomeml.

**Comment by nsorros** [comment]
> The `Automatically load models like en_core_web_sm and en_trf_bertbaseuncased_lg but also download packages like sent2vec` comment could do with a 'when needed' addition at the end? Otherwise people might be worried they are about to load some massive models if they install wellcomeml.

Good point

**Comment by aCampello** [comment]
Looks good. Here is a comparison of the branches:

https://github.com/wellcometrust/WellcomeML/compare/v2020.5.1...master

I think we covered everything
